/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projecttspgreedy;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Barcodew
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradasiPanel1 = new projecttspgreedy.GradasiPanel();
        jPanel1 = new javax.swing.JPanel();
        canvas2 = new projecttspgreedy.Canvas();
        fButton2 = new projecttspgreedy.FButton();
        solutionPane = new javax.swing.JScrollPane();
        solutionArea = new javax.swing.JTextArea();
        fButton3 = new projecttspgreedy.FButton();
        fButton4 = new projecttspgreedy.FButton();
        fTextField1 = new projecttspgreedy.FTextField();
        fButton5 = new projecttspgreedy.FButton();
        fButton6 = new projecttspgreedy.FButton();
        fTextField2 = new projecttspgreedy.FTextField();
        fButton7 = new projecttspgreedy.FButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travelling Salesman Problem");

        gradasiPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(canvas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 890, 880));

        gradasiPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 910, 900));

        fButton2.setText("START PROGRAM");
        fButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton2ActionPerformed(evt);
            }
        });
        gradasiPanel1.add(fButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 200, 50));

        solutionArea.setColumns(20);
        solutionArea.setRows(5);
        solutionPane.setViewportView(solutionArea);

        gradasiPanel1.add(solutionPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 190, 170));

        fButton3.setText("OPEN");
        fButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton3ActionPerformed(evt);
            }
        });
        gradasiPanel1.add(fButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 880, 200, 50));

        fButton4.setText("SAVE");
        fButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton4ActionPerformed(evt);
            }
        });
        gradasiPanel1.add(fButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 820, 200, 50));

        fTextField1.setText(" ");
        fTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTextField1ActionPerformed(evt);
            }
        });
        fTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fTextField1KeyTyped(evt);
            }
        });
        gradasiPanel1.add(fTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 100, 50));

        fButton5.setText("RESET");
        fButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton5ActionPerformed(evt);
            }
        });
        gradasiPanel1.add(fButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 760, 200, 50));

        fButton6.setText("RANDOM");
        fButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton6ActionPerformed(evt);
            }
        });
        fButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fButton6KeyTyped(evt);
            }
        });
        gradasiPanel1.add(fButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 100, 50));

        fTextField2.setText(" ");
        fTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTextField2ActionPerformed(evt);
            }
        });
        fTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fTextField2KeyTyped(evt);
            }
        });
        gradasiPanel1.add(fTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 100, 50));

        fButton7.setText("SET DEPOT");
        fButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton7ActionPerformed(evt);
            }
        });
        gradasiPanel1.add(fButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projecttspgreedy/TSPGreedy__2.png"))); // NOI18N
        gradasiPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 20, 390, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradasiPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradasiPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1276, 1004));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextField1ActionPerformed

    private void fTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextField2ActionPerformed

    private void fButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton6ActionPerformed
        String sRandom = fTextField1.getText().trim();
        if ( sRandom == "" || sRandom == null){
               canvas2.randomVertex(5);
        }else{
                int iRandom = Integer.parseInt(sRandom);
                canvas2.randomVertex(iRandom);
        }
    }//GEN-LAST:event_fButton6ActionPerformed

    private void fButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton2ActionPerformed
        canvas2.runGreedyTSP();
        solutionArea.setText("Path : "+canvas2.solusiTSPGreedy);
        solutionArea.append("\n\nDistance : "+canvas2.hitungBobot());
    }//GEN-LAST:event_fButton2ActionPerformed

    private void fButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton7ActionPerformed
        String sDepot = fTextField2.getText().trim();
        System.out.println(sDepot);
        if(sDepot == ""|| sDepot == null){
        JOptionPane.showMessageDialog(this,"Masukkan Angka bro!");
    }else{
             int iDepot = Integer.parseInt(sDepot);
            if(iDepot>=0&&iDepot<canvas2.listTitik.size()){
            canvas2.verTextDepot=iDepot;
            canvas2.repaint();
                } 
        }

    }//GEN-LAST:event_fButton7ActionPerformed

    private void fButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton5ActionPerformed
        canvas2.resetGraph();
        solutionArea.setText("");
        
    }//GEN-LAST:event_fButton5ActionPerformed

    private void fButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton4ActionPerformed
        canvas2.save();
    }//GEN-LAST:event_fButton4ActionPerformed

    private void fButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton3ActionPerformed
        canvas2.open();
    }//GEN-LAST:event_fButton3ActionPerformed

    private void fTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTextField2KeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fTextField2KeyTyped

    private void fButton6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fButton6KeyTyped

    }//GEN-LAST:event_fButton6KeyTyped

    private void fTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTextField1KeyTyped
                       char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_fTextField1KeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
        
          try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ignored) {
            Toolkit.getDefaultToolkit().beep();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            ex.printStackTrace();
            return;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projecttspgreedy.Canvas canvas2;
    private projecttspgreedy.FButton fButton2;
    private projecttspgreedy.FButton fButton3;
    private projecttspgreedy.FButton fButton4;
    private projecttspgreedy.FButton fButton5;
    private projecttspgreedy.FButton fButton6;
    private projecttspgreedy.FButton fButton7;
    private projecttspgreedy.FTextField fTextField1;
    private projecttspgreedy.FTextField fTextField2;
    private projecttspgreedy.GradasiPanel gradasiPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea solutionArea;
    private javax.swing.JScrollPane solutionPane;
    // End of variables declaration//GEN-END:variables
}
